; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;-------------------BOARD SELECTION------------------------------------------
;-------I work with two different boards: Firebeetle ESP32 and Wemos ESP-Uno (arduino form factor ESP32)
;---Other boards can be added here as required.
;---Uncomment these two lines for wemos_d1_uno32, comment out for another other board
;[env:wemos_d1_uno32]
;board = wemos_d1_uno32
;---Uncomment these two lines for firebeetle, comment out the lines for any other board

[base_config]
monitor_speed = 115200
lib_ldf_mode=deep 
monitor_filters = esp32_exception_decoder
build_flags =
    '-D _WIFI_SSID="${sysenv.WIFI_SSID}"'
    '-D _WIFI_PASSWORD="${sysenv.WIFI_PASSWORD}"'


[live]
lib_deps=
  https://github.com/bryanclarkedev/beluga_utils
  https://github.com/bryanclarkedev/beluga_arduino_utils
  https://github.com/bryanclarkedev/beluga_core 
  

[dev]
lib_deps = 
  https://github.com/adafruit/Adafruit_Sensor.git  
  https://github.com/adafruit/Adafruit_BusIO.git  
  https://github.com/adafruit/Adafruit_BMP280_Library.git
  https://github.com/RobTillaart/SD2405.git
  https://github.com/knolleary/pubsubclient.git
  https://github.com/winocc/MAX17043
  https://github.com/terrorsl/sMQTTBroker
  olikraus/U8g2
  ;https://github.com/olikraus/u8g2
  ;When developing, use local library copies to avoid having to git push-git pull the depencies.
  ;lib_extra_dirs =
  symlink:///home/bryan/src/beluga_arduino_utils
  symlink:///home/bryan/src/beluga_utils
  symlink:///home/bryan/src/beluga_core
  #C:\workspace\github\beluga\beluga_arduino_utils
  #C:\workspace\github\beluga\beluga_utils
  #C:\workspace\github\beluga\beluga_core

  ;symlink://../../


[env:esp32-c3]
extends = base_config
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_ldf_mode = deep+
build_flags=
  ${base_config.build_flags} 
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DESP32C3=1
  -DESP32BOARD="C3"

lib_deps = ${dev.lib_deps}

[env:firebeetle32]
extends = base_config
board = firebeetle32
;--------------------------------------------------------------------------
platform = espressif32
;Change partitions to support SPIFFS filesystem
#board_build.partitions = default_16MB.csv
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = min_spiffs.csv
framework = arduino
build_flags =
    ${base_config.build_flags}
    -DDEVICE_NAME="MyDevice"
    -DESP32BOARD="FIREBEETLE"
    -DFIREBEETLE=1

lib_deps = ${dev.lib_deps}



[env:geekmagicclock]
extends = base_config
board = esp32dev
;--------------------------------------------------------------------------
platform = espressif32
;Change partitions to support SPIFFS filesystem
#board_build.partitions = default_16MB.csv
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = min_spiffs.csv
framework = arduino
build_flags =
    ${base_config.build_flags}
    -DDEVICE_NAME="MyDevice"
    -DESP32BOARD="GEEKMAGIC"
    -DFIREBEETLE=1

lib_deps = ${dev.lib_deps}


[env:m5stickc]
extends = base_config
board = m5stick-c
;--------------------------------------------------------------------------
platform = espressif32
;Change partitions to support SPIFFS filesystem
#board_build.partitions = default_16MB.csv
board_build.flash_mode = dio
#board_build.f_flash = 40000000L
board_build.partitions = min_spiffs.csv
framework = arduino
build_flags =
    ${base_config.build_flags}
    -DDEVICE_NAME="MyDevice"
    -DESP32BOARD="M5STICKC"
    -DFIREBEETLE=1

lib_deps = ${dev.lib_deps}


[env:final]
extends = env:firebeetle32
